spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agriconnect
    username: agriconnect
    password: agriconnect
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
